### ISSUE TITLE
Support for karma 0.13.x

### ISSUE THREAD

**Issue by cajoy** [dmitriiabramov/karma-json-fixtures-preprocessor#7]
Can we add support for Karma 0.13.x?

Or at least update package.json?

**Comment by dmitriiabramov** [comment]
i tested against 0.13 and it worked. so i updated `package.json`
https://github.com/dmitriiabramov/karma-json-fixtures-preprocessor/commit/bd92e8547a22856d4fdd6df4243e6133913f3fc7

thanks for bringing it up!
