### ISSUE TITLE
Only loading first file

### ISSUE THREAD

**Issue by soupman99** [dmitriiabramov/karma-json-fixtures-preprocessor#8]
I'm only able to get this plugin to load my first JSON file.  Is this the expected behavior?

**Comment by dmitriiabramov** [comment]
@soupman99 it should not be.
can you provide an example to reproduce the problem?

**Comment by soupman99** [comment]
Here's a gist of my karma.conf.js

https://gist.github.com/soupman99/1cd68b3b5e92910884e7

Is that enough to tell what's going on or not?

**Comment by soupman99** [comment]
Nevermind I got it working now.  Nothing like starting again from an older version of the file ;)

**Comment by dmitriiabramov** [comment]
@soupman99 no worries... i wrote a test that reads two files here https://github.com/dmitriiabramov/karma-json-fixtures-preprocessor/pull/9
so you can use it as a working example
